version: '3.9'

services:
  web:
    build: .
    command: python /django/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=_mz%bpwujmc*f9z3enxuj!(kd0fn3lu4(r%2tmwb5d+b$$y%%@9"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data: